version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "database"
    ports:
      - "5432:5432"
